apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: istio-control
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: trafficdirector.googleapis.com:443

      # Envoy proxy port to listen on for the admin interface.
      proxyAdminPort: 15000

      proxyMetadata:
        # GCP Project number where Traffic Director resources are configured.
        # This is a numeric identifier of your project (e.g. "111222333444").
        # You can get a list of all your projects with their corresponding numbers by
        # using "gcloud projects list" command or looking it up under "Project info"
        # section of your GCP console.
        # If left empty, configuration will be attempted to be fetched for the GCP
        # project associated with service credentials.
        # Leaving empty is not recommended as it is not guaranteed to work in future
        # releases.
        TRAFFICDIRECTOR_GCP_PROJECT_NUMBER: "636150303269"

        # GCP VPC network name for which the configuration is requested (This is the VPC
        # network name referenced in the forwarding rule in GCP API). If left empty,
        # configuration will be attempted to be fetched for the VPC network over which
        # the request to Traffic Director (trafficdirector.googleapis.com) is sent out.
        # Leaving empty is not recommended as it is not guaranteed to work in future
        # releases.
        TRAFFICDIRECTOR_NETWORK_NAME: "default"
---
