apiVersion: v1
kind: Service
metadata:
  name: service-hello
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    run: app
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app-asia
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/serve-hostname-amd64:1.1
        name: app
        command:
        - /bin/sh
        - -c
        - /serve_hostname -http=true -udp=false -port=80
        ports:
        - protocol: TCP
          containerPort: 80
